export const POST_STARTINTERVIEW_LOADING = 'POST_STARTINTERVIEW_LOADING';
export const POST_STARTINTERVIEW_ERROR = 'POST_STARTINTERVIEW_ERROR';
export const POST_STARTINTERVIEW_SUCCESS = 'POST_STARTINTERVIEW_SUCCESS';