export const POST_CREATEUSER_LOADING = "POST_CREATEUSER_LOADING";
export const POST_CREATEUSER_ERROR = "POST_CREATEUSER_ERROR";
export const POST_CREATEUSER_SUCCESS = "POST_CREATEUSER_SUCCESS";

export const POST_LOGIN_LOADING = "POST_LOGIN_LOADING";
export const POST_LOGIN_ERROR = "POST_LOGIN_ERROR";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";

export const GET_LOGOUT_LOADING = "GET_LOGOUT_LOADING";
export const GET_LOGOUT_ERROR = "GET_LOGOUT_ERROR";
export const GET_LOGOUT_SUCCESS = "GET_LOGOUT_SUCCESS";

export const GET_LOGGEDUSER_LOADING = "GET_LOGGEDUSER_LOADING";
export const GET_LOGGEDUSER_ERROR = "GET_LOGGEDUSER_ERROR";
export const GET_LOGGEDUSER_SUCCESS = "GET_LOGGEDUSER_SUCCESS";
